# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/hp/phobos/setup-makefiles.sh
# Herda os blobs reais
$(call inherit-product, vendor/hp/phobos/phobos-vendor-blobs.mk)


# Ignora o arquivo blobs.mk obsoleto
PRODUCT_SOONG_NAMESPACES += vendor/hp/phobos

# Configura vendor partition
PRODUCT_PACKAGES += \
    libGLESv2_tegra \
    gralloc.tegra4 \
    hwcomposer.tegra4

PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(LOCAL_PATH)/proprietary,vendor)
